# Generated by Django 3.1 on 2020-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Type_user',
            field=models.IntegerField(choices=[(1, 'قطاعي'), (2, 'جملة')], default=1, verbose_name='نوع المستخدم'),
        ),
    ]
