#!/usr/bin/python

from .Adafruit_Thermal import *
import datetime
datetime_now = datetime.datetime.now()
printer = Adafruit_Thermal("/dev/serial0", 19200, timeout=5)

def printHeader():
    printer.justify('C')
    printer.boldOn()
    printer.setSize('L')
    printer.setLineHeight(50)
    printer.println("----------------")
    printer.println()
    printer.println("ADPD")
    printer.boldOff()
    printer.setSize('M')
    printer.println("Jeddah, Saudi Arabia.")
    printer.setSize('S')
    printer.println(datetime_now)
    printer.boldOn()
    printer.println()
    printer.setSize('M')
    printer.println("Invoice")
    printer.boldOff()
    printer.setSize('L')
    printer.println("----------------")
    printer.justify('L')
    printer.setSize('S')
    printer.println("Item\tQty\tPrice\tTotal")
    printer.setSize('L')
    printer.println("----------------")
def printItem(Name,Qty,Price):
    printer.justify('L')
    printer.setSize('S')
    printer.print(Name+"\t"+str(Qty)+"g  \t"+str(Price)+"SR/g\t "+str(Qty*Price)+"SR\n")
def printFooter(total):
    printer.justify('L')
    printer.setSize('L')
    printer.println("----------------")
    printer.setSize('S')
    printer.boldOn()
    printer.println("TOTAL\t\t\t\t"+str(total)+" SR")
    printer.boldOff()
    printer.setSize('L')
    printer.println("----------------")
    printer.setSize('S')
    printer.justify('C')
    printer.println("Thank you for your purchase")
    printer.println("Have a nice day!")
    printer.setSize('L')
    printer.println("----------------")
    printer.println()
printHeader()
printItem("Peanuts",2,0.4)
printItem("Coffee",50,0.8)
printItem("Pasta",100,1)
printFooter(300)