# Generated by Django 3.1.6 on 2021-03-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpdapp', '0004_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
