# Generated by Django 3.1.6 on 2021-03-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpdapp', '0005_auto_20210310_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
