# Generated by Django 3.1.6 on 2021-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpdapp', '0006_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=50, verbose_name='price'),
        ),
    ]
