# Generated by Django 3.1.7 on 2021-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpdapp', '0009_auto_20210319_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, max_digits=50, verbose_name='price'),
        ),
    ]
